// <auto-generated />
using KnihovnaEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnihovnaEF.Migrations
{
    [DbContext(typeof(KnihovnaContext))]
    partial class KnihovnaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("KnihovnaEF.Kniha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegalId");

                    b.ToTable("Knihy");
                });

            modelBuilder.Entity("KnihovnaEF.Regal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nazev")
                        .IsUnique();

                    b.ToTable("Regaly");
                });

            modelBuilder.Entity("KnihovnaEF.Kniha", b =>
                {
                    b.HasOne("KnihovnaEF.Regal", "Regal")
                        .WithMany("Knihy")
                        .HasForeignKey("RegalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regal");
                });

            modelBuilder.Entity("KnihovnaEF.Regal", b =>
                {
                    b.Navigation("Knihy");
                });
#pragma warning restore 612, 618
        }
    }
}
