// <auto-generated />
using EntityFrameworkIntro;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkIntro.Migrations
{
    [DbContext(typeof(SkolaContext))]
    [Migration("20260121102040_InicializaceDB")]
    partial class InicializaceDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("EntityFrameworkIntro.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("EntityFrameworkIntro.Trida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tridy");
                });
#pragma warning restore 612, 618
        }
    }
}
